# https://docs.travis-ci.com/user/docker/

# https://docs.travis-ci.com/user/conditions-v1

#.travis.yml
dist: bionic

language: node_js
node_js:
  - 10
cache: yarn

# install:
#   - yarn build

env:
  global:
    - DRY_RUN: FALSE
    - FIREBASE_PROJECT: preactjs-projects
    # SLACK_TOKEN, build-bot
    - secure: rrPSP7MtHyLwwId3n+TH2LHpPm0gWLDuxGA10uFbEN11ImJzMX0gtfQhrxJ9i5ThNHLLZwTsTcj9XsBV3j8K/iayIMe3iHA9MLvQIuKSDMI8v+96eVpWZvLZlBfR/YWlHq7CcZeLuvphnrBTReYT4pq3kIYRysez0sRni8Kiz+iV7GzmeeLHGzRJVx+urG3JAJiL8cM6oqJOu+AUblOHQqJCs6gaXHEvcGG4EMFaT4+LFrzlU2LGgKLgGpH6tUWsr1JEnzhUTy1i7ZFo1UCHF8igG7PnsuV+2UEZzpXZaj4jC1xj+MUASRzjqbBUaOHuXd2r5XxI8Ga+3qKTDFrMgPis1SEZ69IOMhqq6W6VHMxfWS/q+aL3/2p5HhQ6Q0xbBqrLF70ULqucXcflDQzFqcKGG05e8B+ctosoATmOQIOAjY884bZwgFmiiM7tK2/4U89/wHanwH5tMRHDcNv7dyacvBzbQz6IpimbG9GSSBkddwDWOMjTA3TSkKyhRthT/nEjUYjRokCD2q0m+dURgIO2Mc01BSZWJQ4jl7Ef2FFFsbven4JIipQBwCo5L5TaqMObG23tiLOAioONqmqBn6FCQ0dpFvwqNEJDcbdwfyz6B4OgKxlqm4fYHJmrAPdN1U8R6AnmAvd5j2YwWT/7+zIQ7jpDUvJIDiuJprr03Wo=

    # GITHUB_TOKEN
    - secure: XGFnCBPHGNEJwdRw7CVuUsQukmNM8t+ivvzUBFkxXeLUDza1sU7cjVHyQQH8DAbUu7LaOIE8P0tEcIbxOsI/btfdPqixdVBaaSwJxLSVSy9UQBI3VWdaB++VgVGlLCapL+oWrRuIbjBt7BwsVtud32v0m3suo6PhYa8j5eR/a2E8bxwSPjeTC62vOK8R7JeUMPWrqzzowmSR5Te0RzKubSYYzhMB1PzrXfy06/CQihH/jlCi/jxe4aFivVUFG/Tonvnu8O25J26TlNB2cHJfFAXba1oIE8tJrPvWzAnJtBbyHsvJi2cbnr7DFCiky0HrnGh9twa6erA/Bia2fRVUEyhO5SEltE4ceezRcVaXBNT2W9lkzfJluuBVPD0MTvl6URQIecmg27H8nR1/tS92khlSrPgollkKIbPkGMTLE10/xRp9lWv640TGVaFARz/xy2Af7WTbcj5nq0ePiDSirfHWfrik+bCnAWLJ2JR9uCsjZeIYY8hym3kbvNcl12WzLlI8mESGHQR6v+4zPkhNKfyJjJQp/dRen/sWFBr74+hnfMDuF2NSnu9tHe1UqQ3gbhn5GwVIm2704wQ0gUG0gLuY0RuCp+0WH11smKMNNSFOKRfhKXQUa2ssgpvZukQDih/zvoKqT4WTUYNj6Ocruzov/sKyM2zl5idF9OQF4Gw=

    # FIREBASE_TOKEN
    - secure: hu7esNhvwkl6oajEQf2A3F1FCZtgibdZnTpXPegcLBPiIGQvE7Yk4uyrp9jQlXqfikJsQvD/yfTWH3doEhsTCY/SOKm8Gqrr6LAzlKQnMEvTPrPW840DTrwF7f4cefT4bAj1gx2yV+LL9nV8ja0xaIJaUsyK2Q0v82jSoOKvmJi3uOFpzKfdePbxAP2k1a1ACs5DtzsJ8Ku2V6eB0mjlqQFIhVw4v4tfqfGHVCMQEdZbKWT+UeZOUW4QmIc4iRi2rhJU5iK0zbMwUYnn6Z0gGUxSWdSMCzNHds3gU9fcU1OH3rE8DENG9Fz06zrIUM7pmXGAXltP8p+qMNy/9pQjIfSmmEb2pkEA6gYRsCkZ0f+ZgcleOMPF2Sy1raIrqTdKzeS0voFlhVw5GK+Z9id2GPUA64gkkbvaaiaB6QuSQaW6ZaKnl9YOFcRl8M7b9qiL2dVONKwXYe/RoO8HZA7yZBZNOdbNp3bQv9Bsj+DEijfq3m6PSeqFCiWfqHsMMK1A+ghMrMZpdDE56R22Q1XacAsmOUjY4ecBUYK+HhkUBPastsa+Ay32l8gIgHROf7a9KMIQ64/7mDdpxlDE6yQqgdDNr1kDTmguZ7AFN/U9y9NTozhgqgul4qy+ZEfUId2X/VY/GKWlgvf/12IspCgxtXTN6Pq2xd5GMpL2G+esD8w=

notifications:
  slack:
    secure: mqz4tXHCbavb6OKIdsDutgGJDpSI8UiGOjtOT1NbUUa0kFVXmNetM66tLSZO8dIotcVCLuoykq+LrcO3bjcVjm85moS0vb+3hjdZGGQF9wl6iQrJax+vVfQGxtiESzVpc1jP+ypVVLmhRkx+09uQMoeNdr8bjN0PuKXGZU2qjwMkHvhZbAQGbfm4xKllBWf9nlnbEKZZzGgJpN4x+BAcp9hquKLCFVAH7u6ofokX7Q9TYFoHAghpNQEQLI7WVEVjjuhk5EELqQbWTLdNrVeiDt8F8l4XEGPjjy+FqPTzV/vc4QXCwSo9vO+T+C5uDrKYQGKV61Vni663tobx/KtYWooHNV2Lc653YQrKDRM3318cv4RofnVGXM6Vog9n9ppDTMPZdPdc1ifXoL3a4MesbXpJOQUynXJTqQyZtFxKlru1jMWyYJ5/IsIXcJxIbnaUT4Tuf4EL8XRHuvO8IX4mjPAd2gjNxPgoTbvKToJIMFXURzOD9GIlCKSUgS7CONdiRzzib6lKin3gGe7qwoTHq8hGGuqCXpQziaN385fEBvC5dm0X8R+nigXSKz53rP/jPv62V0kOsyNyKL6TLeBOURx8gnTAXe0WZRvvKSyPh9SXfXsRBkkww4Kaavn38siMqSD9yRhf7LAqctJI1IuUOSFhTrG9q+mhzNGGSSa8L2Q=

jobs:
  include:
    - stage: Build
      name: "Build preact app"
      script:
        - yarn build | tee yarn_build.log

    - stage: "Deploy"
      name: "Deploy to firebase"

      script:
        - npm install -g firebase-tools firebase-functions firebase-admin
        - node ./scripts/update_build_info.js
        - yarn build
        - ls -l build
      deploy:
        # production deploy
        - provider: script
          on:
            all_branches: true
            condition: $TRAVIS_BRANCH = "master" -a "$DRY_RUN" = "FALSE"
          script: firebase deploy --project $FIREBASE_PROJECT --only hosting:production --token $FIREBASE_TOKEN --non-interactive
        # staging deploy
        - provider: script
          on:
            all_branches: true
            condition: $TRAVIS_BRANCH = "develop" -a "$DRY_RUN" = "FALSE"
          script: firebase deploy -f --project $FIREBASE_PROJECT --only hosting:staging --token $FIREBASE_TOKEN --non-interactive

    - stage: Merge
      script:
        - if [ "$DRY_RUN" = "FALSE" ]; then ./.travis/merge_if_success.sh; fi

after_failure:
  - cat yarn_build.log
# TODO: remove me
# import:
# - .travis/env.yml
# - .travis/build.yml
# - .travis/merge.yml
# - .travis/deploy.yml
# after_success:
#   - cd _util
#   - id
#   - sudo apt update
#   - sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
#   - pip3 install --user pipenv
#   - pipenv sync
#   - pipenv run python3 ./merge.py
#   - cd ..
