# https://docs.travis-ci.com/user/docker/

#.travis.yml
dist: bionic

language: node_js
node_js:
  - 10
cache: yarn

# install:
#   - yarn build

stages:
  - build
  - deploy
  - merge

import:
  - .travis/env.yml
  - .travis/build.yml
  - .travis/deploy.yml
  - .travis/merge.yml
# after_success:
#   - cd _util
#   - id
#   - sudo apt update
#   - sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
#   - pip3 install --user pipenv
#   - pipenv sync
#   - pipenv run python3 ./merge.py
#   - cd ..
