# https://docs.travis-ci.com/user/docker/

#.travis.yml
sudo: false

dist: trusty

language: node_js
node_js:
  - 8
cache: yarn

# install:
#   - yarn build

script:
  - yarn build

before_deploy:
  - npm install -g firebase-tools firebase-functions firebase-admin

after_script:
  - cd _util
  - id
  - sudo apt update
  - sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
  - pip3 install --user pipenv
  - pipenv sync
  - pipenv run python3 ./merge.py

deploy:
  # production deploy
  - provider: script
    skip_cleanup: true
    script: firebase deploy --project $FIREBASE_PROJECT --only production --token $FIREBASE_TOKEN --non-interactive
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH = "master" && $TRAVIS_NODE_VERSION = $FIREBASE_NODE_VER

  # staging deploy
  - provider: script
    skip_cleanup: true
    script: firebase deploy -f --project $FIREBASE_PROJECT --only staging --token $FIREBASE_TOKEN --non-interactive
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH = "develop" && $FIREBASE_DEV_DEPLOY = "true" && $TRAVIS_NODE_VERSION = $FIREBASE_NODE_VER

env:
  global:
    - FIREBASE_PROJECT: preactjs-projects
    # SLACK_TOKEN
    - secure: K1RymNGUBkH/evDkrFWXEK/jpSioqZhJqkCrtd4VCj0oW8PHtL49wthPqeQ3B+XpP3MFu5vx3N0AQGVRed+rShYDoh49YOc02142r8nBvIwYeTrlH7Ws8M6ZWsElqvzi5g0XprDYs9CmLGvvQDlcVaFIaPwXl67r1H3QQtyLhI7D0DS+j7nI0DsHYZv62Vdg8pn0kYb0Ekm3Am7Efj7AoCG8s4CG8luGPYK795kYs0kqGwyj6Zk5HcwqC7PDqqkFh3KPfnk5NCmKXycg4ZaSDD6fqAAQ8C2+GddaTqTNMoFOp3kvoGMk16UIUdFB/crK+D0nBMiKjgFafy+ENh73NPtfld9bP5QhV0eGrpQYvoGIGUk+KN0C0sQW/u9MqXjuEkAA+Ud3wr0lQ1H+qL3j3B2wH8J5oOgDd+Y/b4JMhbcgjrFzyoIBSRqqasbqopgW/jytz/hs4jcQpIJ2zwQQ8hz9h4WfTVsvxFITBu+Dj3YQGZfbMKF8zmRXNRLqOLKefRbxppVqt0l38u4WlFjHbQIl9JanApGg3JSoT+85RkfCGARV1Nk7puiQIAJlK45pruvqg9qNusl6qG+OhOUh7/oHKdHj3VHyDpdvwL2LUTMXtTG+tavyKdtrMOr/TU00H+WyyifM+yd+64eiXHDjInZscrrXL5QN0fvSkWTi7yA=

    # GITHUB_TOKEN
    - secure: XGFnCBPHGNEJwdRw7CVuUsQukmNM8t+ivvzUBFkxXeLUDza1sU7cjVHyQQH8DAbUu7LaOIE8P0tEcIbxOsI/btfdPqixdVBaaSwJxLSVSy9UQBI3VWdaB++VgVGlLCapL+oWrRuIbjBt7BwsVtud32v0m3suo6PhYa8j5eR/a2E8bxwSPjeTC62vOK8R7JeUMPWrqzzowmSR5Te0RzKubSYYzhMB1PzrXfy06/CQihH/jlCi/jxe4aFivVUFG/Tonvnu8O25J26TlNB2cHJfFAXba1oIE8tJrPvWzAnJtBbyHsvJi2cbnr7DFCiky0HrnGh9twa6erA/Bia2fRVUEyhO5SEltE4ceezRcVaXBNT2W9lkzfJluuBVPD0MTvl6URQIecmg27H8nR1/tS92khlSrPgollkKIbPkGMTLE10/xRp9lWv640TGVaFARz/xy2Af7WTbcj5nq0ePiDSirfHWfrik+bCnAWLJ2JR9uCsjZeIYY8hym3kbvNcl12WzLlI8mESGHQR6v+4zPkhNKfyJjJQp/dRen/sWFBr74+hnfMDuF2NSnu9tHe1UqQ3gbhn5GwVIm2704wQ0gUG0gLuY0RuCp+0WH11smKMNNSFOKRfhKXQUa2ssgpvZukQDih/zvoKqT4WTUYNj6Ocruzov/sKyM2zl5idF9OQF4Gw=

    # FIREBASE_TOKEN
    - secure: hu7esNhvwkl6oajEQf2A3F1FCZtgibdZnTpXPegcLBPiIGQvE7Yk4uyrp9jQlXqfikJsQvD/yfTWH3doEhsTCY/SOKm8Gqrr6LAzlKQnMEvTPrPW840DTrwF7f4cefT4bAj1gx2yV+LL9nV8ja0xaIJaUsyK2Q0v82jSoOKvmJi3uOFpzKfdePbxAP2k1a1ACs5DtzsJ8Ku2V6eB0mjlqQFIhVw4v4tfqfGHVCMQEdZbKWT+UeZOUW4QmIc4iRi2rhJU5iK0zbMwUYnn6Z0gGUxSWdSMCzNHds3gU9fcU1OH3rE8DENG9Fz06zrIUM7pmXGAXltP8p+qMNy/9pQjIfSmmEb2pkEA6gYRsCkZ0f+ZgcleOMPF2Sy1raIrqTdKzeS0voFlhVw5GK+Z9id2GPUA64gkkbvaaiaB6QuSQaW6ZaKnl9YOFcRl8M7b9qiL2dVONKwXYe/RoO8HZA7yZBZNOdbNp3bQv9Bsj+DEijfq3m6PSeqFCiWfqHsMMK1A+ghMrMZpdDE56R22Q1XacAsmOUjY4ecBUYK+HhkUBPastsa+Ay32l8gIgHROf7a9KMIQ64/7mDdpxlDE6yQqgdDNr1kDTmguZ7AFN/U9y9NTozhgqgul4qy+ZEfUId2X/VY/GKWlgvf/12IspCgxtXTN6Pq2xd5GMpL2G+esD8w=




notifications:
  slack:
    secure: mqz4tXHCbavb6OKIdsDutgGJDpSI8UiGOjtOT1NbUUa0kFVXmNetM66tLSZO8dIotcVCLuoykq+LrcO3bjcVjm85moS0vb+3hjdZGGQF9wl6iQrJax+vVfQGxtiESzVpc1jP+ypVVLmhRkx+09uQMoeNdr8bjN0PuKXGZU2qjwMkHvhZbAQGbfm4xKllBWf9nlnbEKZZzGgJpN4x+BAcp9hquKLCFVAH7u6ofokX7Q9TYFoHAghpNQEQLI7WVEVjjuhk5EELqQbWTLdNrVeiDt8F8l4XEGPjjy+FqPTzV/vc4QXCwSo9vO+T+C5uDrKYQGKV61Vni663tobx/KtYWooHNV2Lc653YQrKDRM3318cv4RofnVGXM6Vog9n9ppDTMPZdPdc1ifXoL3a4MesbXpJOQUynXJTqQyZtFxKlru1jMWyYJ5/IsIXcJxIbnaUT4Tuf4EL8XRHuvO8IX4mjPAd2gjNxPgoTbvKToJIMFXURzOD9GIlCKSUgS7CONdiRzzib6lKin3gGe7qwoTHq8hGGuqCXpQziaN385fEBvC5dm0X8R+nigXSKz53rP/jPv62V0kOsyNyKL6TLeBOURx8gnTAXe0WZRvvKSyPh9SXfXsRBkkww4Kaavn38siMqSD9yRhf7LAqctJI1IuUOSFhTrG9q+mhzNGGSSa8L2Q=
