# https://docs.travis-ci.com/user/docker/

#.travis.yml
dist: bionic

language: node_js
node_js:
  - 10
cache: yarn

# install:
#   - yarn build

stages:
  - Unit_test
  - Test
  - Build
  - Deploy
  - Integration_to_other_repo
  - Publish_dashboard
  - Merge

jobs:
  include:
    - stage: Build
      name: "Build preact app"
      script:
        - yarn build | tee yarn_build.log

    - stage: Merge
      name: "Merge commits"
      script:
        - wget https://raw.githubusercontent.com/louiscklaw/travis-playlist/master/travis-build-merger/merge_if_success.sh
        - chmod +x merge_if_success.sh
        - bash merge_if_success.sh | tee merge.log

    - stage: "Deploy"
      name: "Deploy to firebase"

      script:
        - npm install -g firebase-tools firebase-functions firebase-admin
        - node ./scripts/update_build_info.js
        - yarn build
        - ls -l build

      deploy:
        # production deploy
        - provider: script
          skip_cleanup: true
          script: firebase deploy --project $FIREBASE_PROJECT --only hosting:production --token $FIREBASE_TOKEN --non-interactive
          on:
            all_branches: true
            condition: $TRAVIS_BRANCH = "master"

        # staging deploy
        - provider: script
          skip_cleanup: true
          script: firebase deploy -f --project $FIREBASE_PROJECT --only hosting:staging --token $FIREBASE_TOKEN --non-interactive
          on:
            all_branches: true
            condition: $TRAVIS_BRANCH = "ignore/testing-reorder-stages"

        # debug deploy
        - provider: script
          skip_cleanup: true
          script: echo "helloworld"
          on:
            all_branches: true
            condition: $TRAVIS_BRANCH = "poc/fix-deploy-part"

import:
  # - .travis/env.yml
  - credentials.yml
  # - .travis/build.yml
  # - .travis/merge.yml
  # - .travis/deploy.yml

after_failure:
  - cat yarn_build.log
# after_success:
#   - cd _util
#   - id
#   - sudo apt update
#   - sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
#   - pip3 install --user pipenv
#   - pipenv sync
#   - pipenv run python3 ./merge.py
#   - cd ..

env:
  global:
    - FIREBASE_PROJECT: preactjs-projects

    # FIREBASE_TOKEN
    - secure: hu7esNhvwkl6oajEQf2A3F1FCZtgibdZnTpXPegcLBPiIGQvE7Yk4uyrp9jQlXqfikJsQvD/yfTWH3doEhsTCY/SOKm8Gqrr6LAzlKQnMEvTPrPW840DTrwF7f4cefT4bAj1gx2yV+LL9nV8ja0xaIJaUsyK2Q0v82jSoOKvmJi3uOFpzKfdePbxAP2k1a1ACs5DtzsJ8Ku2V6eB0mjlqQFIhVw4v4tfqfGHVCMQEdZbKWT+UeZOUW4QmIc4iRi2rhJU5iK0zbMwUYnn6Z0gGUxSWdSMCzNHds3gU9fcU1OH3rE8DENG9Fz06zrIUM7pmXGAXltP8p+qMNy/9pQjIfSmmEb2pkEA6gYRsCkZ0f+ZgcleOMPF2Sy1raIrqTdKzeS0voFlhVw5GK+Z9id2GPUA64gkkbvaaiaB6QuSQaW6ZaKnl9YOFcRl8M7b9qiL2dVONKwXYe/RoO8HZA7yZBZNOdbNp3bQv9Bsj+DEijfq3m6PSeqFCiWfqHsMMK1A+ghMrMZpdDE56R22Q1XacAsmOUjY4ecBUYK+HhkUBPastsa+Ay32l8gIgHROf7a9KMIQ64/7mDdpxlDE6yQqgdDNr1kDTmguZ7AFN/U9y9NTozhgqgul4qy+ZEfUId2X/VY/GKWlgvf/12IspCgxtXTN6Pq2xd5GMpL2G+esD8w=
