# https://docs.travis-ci.com/user/docker/

# https://docs.travis-ci.com/user/conditions-v1

#.travis.yml
dist: bionic

language: node_js
node_js:
  - 10
cache: yarn

# install:
#   - yarn build

env:
  - DRY_RUN=FALSE

jobs:
  include:
    - stage: Build
      name: "Build preact app"
      script:
        - yarn build | tee yarn_build.log

    - stage: "Deploy"
      name: "Deploy to firebase"

      script:
        - npm install -g firebase-tools firebase-functions firebase-admin
        - node ./scripts/update_build_info.js
        - yarn build
        - ls -l build
      deploy:
        # production deploy
        - provider: script
          script: firebase deploy --project $FIREBASE_PROJECT --only hosting:production --token $FIREBASE_TOKEN --non-interactive
          on:
            all_branches: true
            condition: $TRAVIS_BRANCH = "master" -a "$DRY_RUN" = "FALSE"
        # staging deploy
        - provider: script
          script: firebase deploy -f --project $FIREBASE_PROJECT --only hosting:staging --token $FIREBASE_TOKEN --non-interactive
          on:
            all_branches: true
            condition: $TRAVIS_BRANCH = "develop" -a "$DRY_RUN" = "FALSE"

import:
  - .travis/env.yml
  # - .travis/build.yml
  # - .travis/merge.yml
  # - .travis/deploy.yml

after_success:
  - ./.travis/merge_if_success.sh

after_failure:
  - cat yarn_build.log
# after_success:
#   - cd _util
#   - id
#   - sudo apt update
#   - sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
#   - pip3 install --user pipenv
#   - pipenv sync
#   - pipenv run python3 ./merge.py
#   - cd ..
